version: '3.9'

services:
  web:
    volumes:
      - .:/app
      - /app/staticfiles
    command: >
      sh -c "watchmedo auto-restart --patterns='*.py' --recursive -- python manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: '1'
