# Generated by Django 5.1.4 on 2025-02-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
