# Generated by Django 5.1.4 on 2024-12-24 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('workNumber', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
