# Generated by Django 5.1.4 on 2024-12-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('companyNationalId', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('document', models.FileField(upload_to='uploads/pdfs')),
                ('officialNewspaper', models.FileField(upload_to='uploads/pdfs')),
                ('companyWebsite', models.CharField(max_length=100)),
                ('companyEmail', models.EmailField(max_length=254)),
                ('connectorName', models.CharField(max_length=50)),
                ('connectorLastname', models.CharField(max_length=50)),
                ('connectorNationalCode', models.CharField(max_length=10)),
                ('connectorPhoneNumber', models.CharField(max_length=11)),
                ('introductionLetter', models.FileField(upload_to='uploads/pdfs')),
            ],
        ),
        migrations.AlterField(
            model_name='realperson',
            name='national_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='realperson',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='realperson',
            name='workNumber',
            field=models.CharField(max_length=11),
        ),
    ]
