# Generated by Django 5.1.4 on 2024-12-24 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0002_legalperson_alter_realperson_national_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalperson',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalperson',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalperson',
            name='stars',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='legalperson',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='realperson',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realperson',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realperson',
            name='stars',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='realperson',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='realperson',
            name='workNumber',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
