# Generated by Django 5.1.4 on 2025-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0002_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
