# Generated by Django 5.1.4 on 2025-02-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0004_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
