# Generated by Django 5.1.4 on 2024-12-26 09:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0004_alter_legalperson_stars_alter_realperson_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalperson',
            name='connectorRole',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='legalperson',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalperson',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
