# Generated by Django 5.1.4 on 2024-12-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0005_legalperson_connectorrole_legalperson_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalperson',
            name='username',
        ),
        migrations.RemoveField(
            model_name='realperson',
            name='username',
        ),
        migrations.AlterField(
            model_name='realperson',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='realperson',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='realperson',
            name='lastName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='realperson',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='realperson',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
