# Generated by Django 5.1.4 on 2025-02-25 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0005_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_plan', to='daddik.subscriptionplan')),
                ('old_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_plan', to='daddik.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
