# Generated by Django 5.1.4 on 2025-02-25 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0006_subscriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one lowercase letter, and one number.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$')]),
        ),
    ]
