# Generated by Django 5.1.4 on 2025-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, upload_to='usr/src/app/uploads/pdfs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introductionLetter',
            field=models.FileField(blank=True, upload_to='usr/src/app/uploads/pdfs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='officialNewspaper',
            field=models.FileField(blank=True, upload_to='usr/src/app/uploads/pdfs'),
        ),
    ]
