# Generated by Django 5.1.4 on 2025-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0008_alter_user_document_alter_user_introductionletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, upload_to='uploads/pdfs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introductionLetter',
            field=models.FileField(blank=True, upload_to='uploads/pdfs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='officialNewspaper',
            field=models.FileField(blank=True, upload_to='uploads/pdfs'),
        ),
    ]
