# Generated by Django 5.1.4 on 2024-12-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0008_alter_realperson_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realperson',
            name='workNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
