# Generated by Django 5.1.4 on 2024-12-31 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0009_alter_realperson_worknumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(choices=[('real', 'Real'), ('legal', 'Legal')], default='real', max_length=20)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('name', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('job', models.CharField(blank=True, max_length=50)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('workNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('companyName', models.CharField(blank=True, max_length=50)),
                ('companyNationalId', models.CharField(blank=True, max_length=11, unique=True)),
                ('document', models.FileField(blank=True, upload_to='uploads/pdfs')),
                ('officialNewspaper', models.FileField(blank=True, upload_to='uploads/pdfs')),
                ('companyWebsite', models.CharField(blank=True, max_length=100)),
                ('companyEmail', models.EmailField(blank=True, max_length=254)),
                ('connectorName', models.CharField(blank=True, max_length=50)),
                ('connectorLastname', models.CharField(blank=True, max_length=50)),
                ('connectorNationalCode', models.CharField(blank=True, max_length=10)),
                ('connectorPhoneNumber', models.CharField(blank=True, max_length=11)),
                ('connectorRole', models.CharField(blank=True, max_length=20)),
                ('introductionLetter', models.FileField(blank=True, upload_to='uploads/pdfs')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('isPremium', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LegalPerson',
        ),
        migrations.DeleteModel(
            name='RealPerson',
        ),
    ]
