# Generated by Django 5.1.4 on 2025-03-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0010_alter_user_document_alter_user_introductionletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='organ',
            field=models.CharField(blank=True, default='all', max_length=50),
        ),
    ]
