# Generated by Django 5.1.4 on 2024-12-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0011_alter_user_companynationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lable',
            field=models.CharField(choices=[('real', 'Real'), ('legal', 'Legal'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
