# Generated by Django 5.1.4 on 2024-12-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0012_alter_user_lable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='username',
        ),
    ]
