# Generated by Django 5.1.4 on 2025-01-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0020_remove_message_content_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
