# Generated by Django 5.1.4 on 2025-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daddik', '0023_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.IntegerField(default=5),
        ),
    ]
